name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

# Add permissions for the GITHUB_TOKEN
permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Build for macOS
      run: |
        xcodebuild clean build -project A-Instant.xcodeproj -scheme A-Instant -configuration Release -derivedDataPath build ARCHS="arm64 x86_64" ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      
    - name: Create app bundle
      run: |
        mkdir -p ./artifacts
        cd build/Build/Products/Release
        # Use ditto to create a zip archive that preserves attributes
        ditto -c -k --sequesterRsrc --keepParent A-Instant.app ../../../../artifacts/A-Instant.zip

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-macos
        path: artifacts/*.zip

    - name: Create Release
      id: create_release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: false
        files: artifacts/A-Instant.zip
        name: A-Instant ${{ github.ref_name }}
        body: |
          A-Instant ${{ github.ref_name }}
          
          ## What's New
          
          Please check the commit history for changes since the last release.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 